/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.burbuja;

import javax.swing.JOptionPane;
import com.algoritmo.BurbujaAlgoritmo;

/**
 *
 * @author Laboratorio
 */
public class Burbuja extends javax.swing.JFrame {

    /**
     * Creates new form Burbuja
     */
    public Burbuja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1vector = new javax.swing.JTextField();
        jButtonOrdenar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaarregloOrdenado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        OrdenarjComboBox1 = new javax.swing.JComboBox();
        limpiarjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TipoOrdenjComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de ingreso"));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setToolTipText("");

        jLabel1.setText("Ingreso de Datos");

        jTextField1vector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1vectorActionPerformed(evt);
            }
        });

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Impresion-Arreglo ordenado"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTextAreaarregloOrdenado.setColumns(20);
        jTextAreaarregloOrdenado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaarregloOrdenado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel2.setText("Selecciona");

        OrdenarjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Selecciona>>", "burbuja", "burbuja mejorada" }));

        limpiarjButton.setText("Limpiar");
        limpiarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TipoOrdenjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecciona>>", "Ascendente", "Descendente" }));

        jLabel3.setText("Selecciona Tipo Ordenamiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1vector, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrdenarjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipoOrdenjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOrdenar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(limpiarjButton)
                        .addComponent(jButton1)))
                .addGap(0, 301, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1vector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOrdenar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OrdenarjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoOrdenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(limpiarjButton)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1vectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1vectorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField1vectorActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        // TODO add your handling code here:
        BurbujaAlgoritmo b = new BurbujaAlgoritmo();
        String arreglo = jTextField1vector.getText().trim();
        
        String seleccionaAreglo =OrdenarjComboBox1.getSelectedItem().toString().trim();
        String SeleccionaTipo=TipoOrdenjComboBox.getSelectedItem().toString().trim();
        
              

        if (arreglo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un Arreglo", "error", JOptionPane.ERROR_MESSAGE);
jTextField1vector.requestFocus();
         
        }else if(seleccionaAreglo.equalsIgnoreCase("<<Selecciona>>")&&SeleccionaTipo.equalsIgnoreCase("<<Selecciona>>")){
            
                JOptionPane.showMessageDialog(null, "Selecciona un metodo ordenamiento", "error", JOptionPane.ERROR_MESSAGE);
        //jTextField1vector.requestFocus();
            
            
         } else if (seleccionaAreglo.equalsIgnoreCase("burbuja")&&SeleccionaTipo.equalsIgnoreCase("Ascendente")) {
             
                     String[] arregloV = arreglo.split(",");
             
                       int[] arregloVInt = new int[arregloV.length];
            
            for (int i = 0; i < arregloV.length; i++) {
                // b.burbuja(Integer.parseInt(arregloV[i]));
                arregloVInt[i] = Integer.parseInt(arregloV[i]);

            }

            int[] arregloOrdenado = b.burbuja(arregloVInt);
            
            
             for (int i = 0; i < arregloV.length; i++) {
               jTextAreaarregloOrdenado.append("["+arregloV[i]+"]");
                
            }
             
           jTextAreaarregloOrdenado.append("\n\n");
           
   
            for (int i = 0; i < arregloOrdenado.length; i++) {
                
           
                 jTextAreaarregloOrdenado.append("["+arregloOrdenado[i]+"]");  
                 
                 
               
            }
                 jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont+"]"+"\n");
                   jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont2+"]"+"\n");
            
           

 } else if (seleccionaAreglo.equalsIgnoreCase("burbuja")&&SeleccionaTipo.equalsIgnoreCase("Descendente")) {
           String[] arregloV = arreglo.split(",");

            int[] arregloVInt = new int[arregloV.length];
            for (int i = 0; i < arregloV.length; i++) {
                // b.burbuja(Integer.parseInt(arregloV[i]));
                arregloVInt[i] = Integer.parseInt(arregloV[i]);

            }

            int[] arregloOrdenado = b.burbujaDescendente(arregloVInt);
            
            
             for (int i = 0; i < arregloV.length; i++) {
               jTextAreaarregloOrdenado.append("["+arregloV[i]+"]");
                
            }
             
           jTextAreaarregloOrdenado.append("\n\n");
           
    
            for (int i = 0; i < arregloOrdenado.length; i++) {
                
                 jTextAreaarregloOrdenado.append("["+arregloOrdenado[i]+"]");
                
               
            }
                 jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont+"]"+"\n");
                   jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont2+"]"+"\n");
         
         
         
         
    }else if (seleccionaAreglo.equalsIgnoreCase("burbuja mejorada")) {
            String[] arregloV = arreglo.split(",");

            int[] arregloVInt = new int[arregloV.length];
            for (int i = 0; i < arregloV.length; i++) {
                // b.burbuja(Integer.parseInt(arregloV[i]));
                arregloVInt[i] = Integer.parseInt(arregloV[i]);

            }

            int[] arregloOrdenado = b.burbujaMejorada(arregloVInt);
            
            
             for (int i = 0; i < arregloV.length; i++) {
               jTextAreaarregloOrdenado.append("["+arregloV[i]+"]");
                
            }
             
           jTextAreaarregloOrdenado.append("\n\n");
           
    
            for (int i = 0; i < arregloOrdenado.length; i++) {
                
                 jTextAreaarregloOrdenado.append("["+arregloOrdenado[i]+"]");
                
               
            }
                 jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont+"]"+"\n");
                   jTextAreaarregloOrdenado.append("\n\n Total de pasadas = "+"["+b.cont2+"]"+"\n");
            
             
             
             
         }


    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void limpiarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarjButtonActionPerformed

        jTextAreaarregloOrdenado.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       jTextAreaarregloOrdenado.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burbuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Burbuja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrdenarjComboBox1;
    private javax.swing.JComboBox<String> TipoOrdenjComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaarregloOrdenado;
    private javax.swing.JTextField jTextField1vector;
    private javax.swing.JButton limpiarjButton;
    // End of variables declaration//GEN-END:variables
}
