/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraevaluar;

/**
 *
 * @author ricar
 */
public class calcu extends javax.swing.JFrame {

    /**
     * Creates new form calcu
     */
    public calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1V1 = new javax.swing.JTextField();
        jTextFieldV2 = new javax.swing.JTextField();
        jButton1SUMA = new javax.swing.JButton();
        jButtonRESTA = new javax.swing.JButton();
        jButtonMULTI = new javax.swing.JButton();
        jButtonDIV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRESULTADO = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INGRESE VALOR 1:");

        jLabel2.setText("INGRESE VALOR 2:");

        jTextFieldV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV2ActionPerformed(evt);
            }
        });

        jButton1SUMA.setText("+");
        jButton1SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SUMAActionPerformed(evt);
            }
        });

        jButtonRESTA.setText("-");
        jButtonRESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESTAActionPerformed(evt);
            }
        });

        jButtonMULTI.setText("*");
        jButtonMULTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMULTIActionPerformed(evt);
            }
        });

        jButtonDIV.setText("/");
        jButtonDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIVActionPerformed(evt);
            }
        });

        jTextAreaRESULTADO.setColumns(20);
        jTextAreaRESULTADO.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRESULTADO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1SUMA)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonRESTA)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMULTI)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDIV))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1V1)
                                .addComponent(jTextFieldV2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1SUMA)
                    .addComponent(jButtonRESTA)
                    .addComponent(jButtonMULTI)
                    .addComponent(jButtonDIV))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV2ActionPerformed

    private void jButton1SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SUMAActionPerformed
        // TODO add your handling code here:
        
            Double el1 = Double.parseDouble(jTextField1V1.getText().trim());
            Double el2 = Double.parseDouble(jTextFieldV2.getText().trim());

            Double a = el1 + el2 ;
            
            jTextAreaRESULTADO.setText(jTextAreaRESULTADO.getText().trim() + "\n La suma es:" + a);
            
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1SUMAActionPerformed

    private void jButtonRESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESTAActionPerformed
        // TODO add your handling code here:
        
             Double el1 = Double.parseDouble(jTextField1V1.getText().trim());
            Double el2 = Double.parseDouble(jTextFieldV2.getText().trim());

            Double a = el1 - el2 ;
            
            jTextAreaRESULTADO.setText(jTextAreaRESULTADO.getText().trim() + "\n La Resta es:" + a);
        
    }//GEN-LAST:event_jButtonRESTAActionPerformed

    private void jButtonMULTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMULTIActionPerformed
        // TODO add your handling code here:
             Double el1 = Double.parseDouble(jTextField1V1.getText().trim());
            Double el2 = Double.parseDouble(jTextFieldV2.getText().trim());

            Double a = el1 * el2 ;
            
            jTextAreaRESULTADO.setText(jTextAreaRESULTADO.getText().trim() + "\n La multiplicacion es:" + a);
    }//GEN-LAST:event_jButtonMULTIActionPerformed

    private void jButtonDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDIVActionPerformed
        // TODO add your handling code here:
        
        
             Double el1 = Double.parseDouble(jTextField1V1.getText().trim());
            Double el2 = Double.parseDouble(jTextFieldV2.getText().trim());

            Double a = el1 / el2 ;
            
            jTextAreaRESULTADO.setText(jTextAreaRESULTADO.getText().trim() + "\n La Division es:" + a);
    }//GEN-LAST:event_jButtonDIVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SUMA;
    private javax.swing.JButton jButtonDIV;
    private javax.swing.JButton jButtonMULTI;
    private javax.swing.JButton jButtonRESTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRESULTADO;
    private javax.swing.JTextField jTextField1V1;
    private javax.swing.JTextField jTextFieldV2;
    // End of variables declaration//GEN-END:variables
}
